// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvcer8RWSeddneIZNDHvSSfpRHSsWZ5ik',
    appId: '1:388150270740:web:e209a969cdba6721154001',
    messagingSenderId: '388150270740',
    projectId: 'bookyapp-bdf55',
    authDomain: 'bookyapp-bdf55.firebaseapp.com',
    storageBucket: 'bookyapp-bdf55.appspot.com',
    measurementId: 'G-YZTVCGRLVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Hd7PItl985IzmzV01Q4be-RWsoyHVKY',
    appId: '1:388150270740:android:6bb9b872a1793b84154001',
    messagingSenderId: '388150270740',
    projectId: 'bookyapp-bdf55',
    storageBucket: 'bookyapp-bdf55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUHQlMMoSdM_K66vS0ZuR_ut-uNZSajc',
    appId: '1:388150270740:ios:c1a122ba3a225d5f154001',
    messagingSenderId: '388150270740',
    projectId: 'bookyapp-bdf55',
    storageBucket: 'bookyapp-bdf55.appspot.com',
    iosBundleId: 'com.example.booky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUHQlMMoSdM_K66vS0ZuR_ut-uNZSajc',
    appId: '1:388150270740:ios:62d500663c81e552154001',
    messagingSenderId: '388150270740',
    projectId: 'bookyapp-bdf55',
    storageBucket: 'bookyapp-bdf55.appspot.com',
    iosBundleId: 'com.example.booky.RunnerTests',
  );
}
